### PR TITLE
Add base model

### PR DESCRIPTION
**Pull request by danmichaelo**
Add a base Model for Volume and Bookshelf that provides array access and other convenience methods.

### CODE REVIEW

**Comment by josephmancuso** [comment]
is this ready to be reviewed / pulled / rebased or does it need improvement?

**Comment by danmichaelo** [comment]
Primarily I'd like to know if you can use these new domain objects, since you initially proposed to return `stdClass` objects instead of domain objects. The main idea here is to keep domain objects, but make them  iterable and so on. Any other feedback is also welcome of course.

**Comment by josephmancuso** [comment]
ah ok I see, I'll take a look. I think you're on the right track using the iterator.

this should allow us to using something like `...->all()` and which can return `LibraryBuilder` instance but then when it's thrown inside a foreach, it will just be the data from the `$data` property. Correct me if im wrong, Haven't used a class as an iterator like that before but i've read about them.

If that's the case then it might be a good idea to make the LibraryBuilder extend the model (or possibly make it a trait) and then have almost all data return an instance of LibraryBuilder (like a collection on eloquent or something).

Thoughts?

**Comment by danmichaelo** [comment]
Not totally sure if I get you. `...->all()` on what? The domain object? (Volume/Bookshelf)

And I don't understand why LibraryBuilder should extend Model? The Model is a single model, not a collection, and the iterating is over the properties of the model.

Say you have `$volume = $books->volumes->byIsbn('0521339057')`. Then `$volume` is an instance of `Volume`, and `foreach($volume as $key => $val)` is basically a shortcut for `foreach($volume->data as $key => $val)`. And other stuff like `array_keys($volume)` should also work.

**Comment by danmichaelo** [comment]
Closing this as not planned

**Pull request closed without merging**
